name: Update hub
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  trigger-hub-update:
    uses: krishnans2006-classes/actions/.github/workflows/dispatch-hub-update.yml@main
    with:
      sha: ${{ github.sha }}
      repository: ${{ github.repository }}
    secrets:
      HUB_DISPATCH_PAT: ${{ secrets.HUB_DISPATCH_PAT }}
