name: Update hub
on: [push, workflow_dispatch]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ["krishnans2006-classes/hub"]
    steps:
      - name: Push to repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.HUB_DISPATCH_PAT }}
          repository: ${{ matrix.repo }}
          event-type: update
          client-payload: '{"github": ${{ toJson(github) }}}'
